server:
  name: "mcp-server-time"
  version: "1.0.0"
  host: "localhost"
  port: 8080
  graceful_shutdown_timeout: 30s
  connection_stale_timeout: 2m

time:
  default_timezone: "UTC"
  default_format: "RFC3339"
  supported_formats:
    - "RFC3339"
    - "RFC3339Nano"
    - "Unix"
    - "UnixMilli"
    - "UnixMicro"
    - "UnixNano"
    - "Layout"

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  port: 9080
  path: "/metrics"
